import { boolean, index, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

/**
 * Better Auth's tables, declared in Drizzle so they live in one migration chain
 * and are covered by the CI rebuild-from-zero check.
 *
 * Better Auth does NOT reach the database through Drizzle — its Drizzle adapter
 * requires drizzle-orm >= 0.45.2 and the review confirmed 0.38.4, so it talks to
 * PostgreSQL through the pg Pool directly. These definitions exist so the schema
 * is ours to review and migrate, and so Afrinext code (session revocation, the
 * drift test) can query them typed.
 *
 * The shapes below are not invented: they were generated by Better Auth's own
 * getMigrations() against a scratch database and transcribed, camelCase quoted
 * identifiers included. `authSchemaMatchesBetterAuth` asserts they still match,
 * so a Better Auth upgrade that changes the shape fails a test rather than
 * failing in production.
 *
 * Authentication only. Authorization lives in roles / role_assignments and is
 * never delegated here.
 */
export const authUsers = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("emailVerified").notNull(),
  image: text("image"),
  createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow(),
  phoneNumber: text("phoneNumber").unique(),
  phoneNumberVerified: boolean("phoneNumberVerified"),
});

export const authSessions = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull(),
    ipAddress: text("ipAddress"),
    userAgent: text("userAgent"),
    userId: text("userId").notNull().references(() => authUsers.id, { onDelete: "cascade" }),
    // Afrinext addition via Better Auth's session.additionalFields: payout
    // actions require a re-verification inside the elevation window, so a
    // long-lived session alone is never enough to move money.
    elevatedAt: timestamp("elevatedAt", { withTimezone: true }),
  },
  (t) => [index("session_userId_idx").on(t.userId)],
);

export const authAccounts = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    issuer: text("issuer").notNull(),
    accountId: text("accountId").notNull(),
    providerId: text("providerId").notNull(),
    userId: text("userId").notNull().references(() => authUsers.id, { onDelete: "cascade" }),
    accessToken: text("accessToken"),
    refreshToken: text("refreshToken"),
    idToken: text("idToken"),
    accessTokenExpiresAt: timestamp("accessTokenExpiresAt", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt", { withTimezone: true }),
    scope: text("scope"),
    // Credential hash, managed by Better Auth. Afrinext never reads it.
    password: text("password"),
    createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull(),
  },
  (t) => [
    uniqueIndex("account_issuer_accountId_uidx").on(t.issuer, t.accountId),
    index("account_userId_idx").on(t.userId),
  ],
);

/** Sign-in OTP challenges live here, issued and verified by Better Auth. */
export const authVerifications = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expiresAt", { withTimezone: true }).notNull(),
    createdAt: timestamp("createdAt", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updatedAt", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
);
