import type { Listing } from "./types";

export const SEED_LISTINGS: Listing[] = [
  {
    id: "sahel-grain-collective",
    name: "Sahel Grain Collective",
    tagline: "Millet, sorghum and cowpea straight from the co-op",
    description:
      "A farmer-owned collective of 240 smallholders around Maradi. We aggregate, clean and bag cereals for wholesalers, schools and food processors, with delivery to Niamey twice a week.",
    category: "agriculture",
    city: "Maradi",
    country: "Niger",
    tags: ["wholesale", "cereals", "cooperative"],
    verified: true,
    rating: 4.7,
    reviews: 63,
    priceLabel: "From 18,000 XOF / 50kg bag",
    contact: { phone: "+227 90 00 00 01", email: "hello@sahelgrain.ne" },
    createdAt: "2026-01-14",
  },
  {
    id: "kaduna-cold-chain",
    name: "Kaduna Cold Chain",
    tagline: "Refrigerated haulage for perishables",
    description:
      "Temperature-controlled trucks running the Kaduna–Lagos and Kaduna–Kano corridors. Live tracking on every load, insurance included, and a shared-container option for small shippers.",
    category: "logistics",
    city: "Kaduna",
    country: "Nigeria",
    tags: ["cold chain", "haulage", "tracking"],
    verified: true,
    rating: 4.5,
    reviews: 41,
    priceLabel: "Quote per route",
    contact: { phone: "+234 803 000 0002", website: "https://kadunacoldchain.example" },
    createdAt: "2026-02-02",
  },
  {
    id: "atelier-fatou",
    name: "Atelier Fatou",
    tagline: "Made-to-measure bazin and wax pieces",
    description:
      "A six-person tailoring studio in Medina. We take measurements in person or from a video call, and ship finished garments across West Africa in 10 to 14 days.",
    category: "fashion",
    city: "Dakar",
    country: "Senegal",
    tags: ["tailoring", "bazin", "made to measure"],
    verified: true,
    rating: 4.9,
    reviews: 128,
    priceLabel: "From 35,000 XOF / garment",
    contact: { phone: "+221 77 000 0003", email: "atelier@fatou.sn" },
    createdAt: "2025-11-20",
  },
  {
    id: "nyali-boatworks",
    name: "Nyali Boatworks",
    tagline: "Dhow repair and marine carpentry",
    description:
      "Third-generation boat builders on the Mombasa coast. Hull repair, teak decking and custom furniture milled from offcuts. Dry-dock slots bookable a week ahead.",
    category: "artisans",
    city: "Mombasa",
    country: "Kenya",
    tags: ["carpentry", "marine", "restoration"],
    verified: false,
    rating: 4.4,
    reviews: 22,
    priceLabel: "From KES 6,000 / day",
    contact: { phone: "+254 722 000004" },
    createdAt: "2026-03-08",
  },
  {
    id: "kigali-devworks",
    name: "Kigali Devworks",
    tagline: "Product engineering for African fintechs",
    description:
      "A 14-person studio building payment rails, agent apps and back-office tooling. Comfortable with USSD, mobile money integrations and offline-first mobile clients.",
    category: "tech",
    city: "Kigali",
    country: "Rwanda",
    tags: ["software", "fintech", "mobile money"],
    verified: true,
    rating: 4.8,
    reviews: 37,
    priceLabel: "From $45 / hour",
    contact: { email: "team@kigalidevworks.rw", website: "https://kigalidevworks.example" },
    createdAt: "2026-01-30",
  },
  {
    id: "mama-adjoa-kitchen",
    name: "Mama Adjoa's Kitchen",
    tagline: "Event catering and daily hot lunches",
    description:
      "Ghanaian home cooking at scale: waakye, jollof, kelewele and grilled tilapia. We cater weddings up to 400 covers and run a weekday lunch delivery around Osu and Labone.",
    category: "food",
    city: "Accra",
    country: "Ghana",
    tags: ["catering", "delivery", "events"],
    verified: true,
    rating: 4.6,
    reviews: 210,
    priceLabel: "From GHS 45 / plate",
    contact: { phone: "+233 24 000 0006", email: "orders@mamaadjoa.gh" },
    createdAt: "2025-12-11",
  },
  {
    id: "addis-solar-fitters",
    name: "Addis Solar Fitters",
    tagline: "Rooftop solar and battery backup installs",
    description:
      "Licensed electricians doing 2kW to 20kW installations for homes, clinics and small factories. Two-year workmanship warranty and a maintenance visit every six months.",
    category: "services",
    city: "Addis Ababa",
    country: "Ethiopia",
    tags: ["solar", "electrical", "installation"],
    verified: true,
    rating: 4.5,
    reviews: 74,
    priceLabel: "From ETB 90,000 / system",
    contact: { phone: "+251 91 000 0007", website: "https://addissolar.example" },
    createdAt: "2026-02-19",
  },
  {
    id: "bamako-shea-union",
    name: "Bamako Shea Union",
    tagline: "Unrefined shea butter by the drum",
    description:
      "Women's processing union sourcing nuts from 18 villages in Sikasso. Cold-pressed, filtered and packed in 25kg drums for cosmetics manufacturers, with export paperwork handled.",
    category: "agriculture",
    city: "Bamako",
    country: "Mali",
    tags: ["shea", "export", "wholesale"],
    verified: false,
    rating: 4.3,
    reviews: 19,
    priceLabel: "From 780,000 XOF / drum",
    contact: { email: "union@bamakoshea.ml" },
    createdAt: "2026-03-22",
  },
  {
    id: "harare-print-house",
    name: "Harare Print House",
    tagline: "Screen printing and signage",
    description:
      "Short-run textile printing, vinyl signage and vehicle wraps. Artwork setup is free on orders over 50 units, and we hold plates for repeat runs.",
    category: "artisans",
    city: "Harare",
    country: "Zimbabwe",
    tags: ["printing", "signage", "branding"],
    verified: false,
    rating: 4.1,
    reviews: 15,
    priceLabel: "From $3 / unit",
    contact: { phone: "+263 77 000 0009", email: "print@hph.zw" },
    createdAt: "2026-04-05",
  },
  {
    id: "lome-moto-express",
    name: "Lomé Moto Express",
    tagline: "Same-day parcel runs across the city",
    description:
      "A dispatch fleet of 60 riders covering greater Lomé. Bulk senders get an API and a monthly invoice; everyone else books through WhatsApp with a photo of the parcel.",
    category: "logistics",
    city: "Lomé",
    country: "Togo",
    tags: ["last mile", "same day", "api"],
    verified: true,
    rating: 4.2,
    reviews: 302,
    priceLabel: "From 1,500 XOF / drop",
    contact: { phone: "+228 90 00 0010", website: "https://lomemoto.example" },
    createdAt: "2025-10-02",
  },
  {
    id: "casablanca-datalab",
    name: "Casablanca DataLab",
    tagline: "Analytics and forecasting for retailers",
    description:
      "We plug into point-of-sale exports and return demand forecasts, reorder points and shrinkage alerts. Dashboards in French, Arabic and English.",
    category: "tech",
    city: "Casablanca",
    country: "Morocco",
    tags: ["analytics", "retail", "forecasting"],
    verified: true,
    rating: 4.6,
    reviews: 28,
    priceLabel: "From MAD 4,000 / month",
    contact: { email: "contact@casadatalab.ma" },
    createdAt: "2026-02-27",
  },
  {
    id: "zanzibar-spice-co",
    name: "Zanzibar Spice Co.",
    tagline: "Clove, cardamom and vanilla in bulk",
    description:
      "Direct from Pemba growers. We grade, dry and vacuum-pack for exporters and specialty roasters, with lab certificates on every lot.",
    category: "food",
    city: "Stone Town",
    country: "Tanzania",
    tags: ["spices", "export", "bulk"],
    verified: true,
    rating: 4.7,
    reviews: 56,
    priceLabel: "From TZS 22,000 / kg",
    contact: { phone: "+255 77 000 0012", email: "sales@znzspice.co.tz" },
    createdAt: "2026-01-08",
  },
  {
    id: "abidjan-legal-desk",
    name: "Abidjan Legal Desk",
    tagline: "Company formation and OHADA compliance",
    description:
      "Fixed-fee incorporation, statutes drafting and annual filings for SARL and SA structures. Bilingual counsel and a client portal for document status.",
    category: "services",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    tags: ["legal", "incorporation", "compliance"],
    verified: true,
    rating: 4.4,
    reviews: 47,
    priceLabel: "From 250,000 XOF / filing",
    contact: { email: "desk@abjlegal.ci", website: "https://abjlegal.example" },
    createdAt: "2025-12-30",
  },
  {
    id: "kampala-fabric-market",
    name: "Kampala Fabric Market",
    tagline: "Kitenge, kanga and linen by the bolt",
    description:
      "Wholesale fabric with 400+ patterns in stock. Sample swatches posted free, and we hold reserved bolts for seven days while you decide.",
    category: "fashion",
    city: "Kampala",
    country: "Uganda",
    tags: ["fabric", "wholesale", "kitenge"],
    verified: false,
    rating: 4.0,
    reviews: 33,
    priceLabel: "From UGX 28,000 / 6 yards",
    contact: { phone: "+256 70 000 0014" },
    createdAt: "2026-04-16",
  },
  {
    id: "windhoek-borehole-drilling",
    name: "Windhoek Borehole Drilling",
    tagline: "Water siting, drilling and pump fitting",
    description:
      "Geophysical survey, rotary drilling to 180m, and solar pump installation for farms and lodges. Yield test and water chemistry report included.",
    category: "services",
    city: "Windhoek",
    country: "Namibia",
    tags: ["water", "drilling", "solar pumps"],
    verified: true,
    rating: 4.6,
    reviews: 26,
    priceLabel: "From NAD 1,200 / metre",
    contact: { phone: "+264 81 000 0015", email: "drill@whkwater.na" },
    createdAt: "2026-03-01",
  },
  {
    id: "niamey-repair-hub",
    name: "Niamey Repair Hub",
    tagline: "Phone, laptop and inverter repair",
    description:
      "Board-level electronics repair with a stocked parts counter. Walk-in diagnostics in under an hour, and a courier pickup service for businesses.",
    category: "tech",
    city: "Niamey",
    country: "Niger",
    tags: ["repair", "electronics", "walk-in"],
    verified: false,
    rating: 4.3,
    reviews: 88,
    priceLabel: "From 5,000 XOF / diagnostic",
    contact: { phone: "+227 96 00 0016" },
    createdAt: "2026-04-28",
  },
  {
    id: "jinja-honey-works",
    name: "Jinja Honey Works",
    tagline: "Raw honey, wax and hive equipment",
    description:
      "We run 900 hives along the Nile and buy surplus from 130 outgrower beekeepers. Filtered raw honey in 1kg jars or 20kg pails, plus smokers, suits and frames.",
    category: "agriculture",
    city: "Jinja",
    country: "Uganda",
    tags: ["honey", "beekeeping", "equipment"],
    verified: true,
    rating: 4.8,
    reviews: 71,
    priceLabel: "From UGX 15,000 / kg",
    contact: { email: "hello@jinjahoney.ug", website: "https://jinjahoney.example" },
    createdAt: "2026-02-11",
  },
  {
    id: "douala-freight-forwarders",
    name: "Douala Freight Forwarders",
    tagline: "Customs clearing at the port",
    description:
      "Clearing agents handling import declarations, duty assessment and inland trucking to Yaoundé and N'Djamena. Bonded warehouse space available by the pallet.",
    category: "logistics",
    city: "Douala",
    country: "Cameroon",
    tags: ["customs", "freight", "warehousing"],
    verified: true,
    rating: 4.2,
    reviews: 59,
    priceLabel: "From XAF 180,000 / declaration",
    contact: { phone: "+237 6 99 00 0018", email: "ops@doualaff.cm" },
    createdAt: "2025-11-05",
  },
];
